#!/usr/bin/env python3
"""
Send daily analysis report via email as plain-text table.
"""
import json
import os
import smtplib
import sys
from email.mime.text import MIMEText
from datetime import datetime, timezone, timedelta

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from source_repo import repo_dir_name

TZ_CN = timezone(timedelta(hours=8))
DATA_DIR = "data"


def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def truncate(s, width):
    if not s:
        return "-"
    if len(s) > width:
        return s[:width - 3] + "..."
    return s


def build_table(repos, date_str, data_dir="data"):
    lines = []
    lines.append(f"vLLM Commit Report — {date_str}")
    lines.append("=" * 120)

    for repo in repos:
        repo_dir = repo_dir_name(repo)
        analysis = load_json(f"{data_dir}/{repo_dir}/analysis/{date_str}.json")
        commits_data = load_json(f"{data_dir}/{repo_dir}/commits/{date_str}.json") or {}
        short = repo.split("/")[-1]
        is_vllm = "ascend" not in repo

        if not analysis:
            lines.append(f"\n[{short}] 暂无分析数据")
            continue

        commits = analysis.get("commits", [])
        daily_summary = analysis.get("daily_summary", "")

        # Build commit message map
        message_map = {}
        for c in commits_data.get("commits", []):
            msg = c.get("message", "") or ""
            message_map[c["sha"]] = msg.split("\n")[0]

        # Filter out auto-skipped commits
        visible = [c for c in commits if "自动判定" not in c.get("comment", "")]

        ascend_count = sum(1 for c in visible if c.get("ascend_impact", {}).get("ascend_affected"))
        high_risk_count = sum(1 for c in visible if "high-risk" in c.get("tags", []))
        needs_test_count = sum(1 for c in visible if c.get("test_impact", {}).get("needs_test_update") or c.get("ascend_impact", {}).get("needs_test_update"))
        auto_count = len(commits) - len(visible)

        lines.append(f"\n[{short}]  {len(commits)} commits  |  高风险: {high_risk_count}  |  昇腾影响: {ascend_count}  |  需测试: {needs_test_count}  |  自动跳过: {auto_count}")

        if daily_summary:
            lines.append(f"\n  每日总结: {daily_summary}")

        if not visible:
            lines.append("\n  (所有 commit 均为自动跳过)")
            continue

        # Table header
        cols = ["Commit", "AI分析", "昇腾影响", "测试影响"]
        widths = [52, 30, 30, 24]
        header = "  " + "  ".join(f"{c:<{w}}" for c, w in zip(cols, widths))
        sep = "  " + "  ".join("-" * w for w in widths)
        lines.append(f"\n{header}")
        lines.append(f"  {sep}")

        for c in visible:
            sha_full = c.get("sha", "")
            sha = sha_full[:12]
            gh_url = f"https://github.com/{repo}/commit/{sha_full}"
            commit_title = message_map.get(sha_full, sha)
            if len(commit_title) > 50:
                commit_title = commit_title[:47] + "..."

            comment = c.get("comment", "")
            ai_title = comment.split("\n")[0] if comment else ""

            ascend_info = ""
            test_info = ""
            if is_vllm:
                ai_impact = c.get("ascend_impact", {})
                if ai_impact and ai_impact.get("ascend_affected"):
                    ascend_info = ai_impact.get("functionality", "")
                test_impact = c.get("test_impact", {})
                if test_impact and test_impact.get("needs_test_update"):
                    test_info = test_impact.get("reason", "")
            else:
                test_impact = c.get("test_impact", {})
                if test_impact and test_impact.get("needs_test_update"):
                    test_info = test_impact.get("reason", "")

            row = "  " + "  ".join(
                f"{truncate(v, w):<{w}}" for v, w in zip(
                    [f"{commit_title} ({gh_url})", ai_title, ascend_info, test_info], widths
                )
            )
            lines.append(row)

    lines.append("\n" + "=" * 120)
    lines.append(f"Generated by vLLM Report Bot · {datetime.now(TZ_CN).strftime('%Y-%m-%d %H:%M CST')}")
    return "\n".join(lines)


def send_email(subject, body):
    host = os.environ.get("SMTP_HOST") or "smtp.qq.com"
    port_str = os.environ.get("SMTP_PORT") or "465"
    port = int(port_str) if port_str else 465
    user = os.environ.get("SMTP_USER", "")
    password = os.environ.get("SMTP_PASS", "")
    recipients = os.environ.get("NOTIFY_EMAIL", "").split(",")
    from_addr = os.environ.get("FROM_EMAIL", user)

    if not user or not password or not recipients[0]:
        print("SMTP not configured — skipping email")
        return

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(recipients)

    print(f"From: {user}, To: {recipients}")
    if not recipients or not recipients[0]:
        print("No recipients configured, skipping")
        return

    last_err = None
    for try_port in (465, 587):
        try:
            if try_port == 465:
                server = smtplib.SMTP_SSL(host, 465, timeout=30)
            else:
                server = smtplib.SMTP(host, 587, timeout=30)
                server.starttls()
            server.ehlo()
            server.login(user, password)
            server.sendmail(from_addr, recipients, msg.as_string())
            server.quit()
            print(f"Email sent via port {try_port}")
            return
        except Exception as e:
            last_err = e
            print(f"Port {try_port} failed: {e}")
            continue
    print(f"Failed to send email: {last_err}")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Send daily analysis report via email")
    parser.add_argument("date", nargs="?", default=None, help="Date (YYYY-MM-DD), defaults to today")
    parser.add_argument("--data-dir", default="data", help="Data directory")
    args = parser.parse_args()

    repos = ["vllm-project/vllm", "vllm-project/vllm-ascend"]
    date_str = args.date or datetime.now(TZ_CN).strftime("%Y-%m-%d")

    body = build_table(repos, date_str, data_dir=args.data_dir)
    print(body[:500] + "...")
    subject = f"vLLM Report — {date_str}"
    send_email(subject, body)


if __name__ == "__main__":
    main()
